const Types = {
  READ_USER_REQUEST: '@users/READ_USER_REQUEST',
  READ_USER_SUCCESS: '@users/READ_USER_SUCCESS',

  CREATE_USER_REQUEST: '@users/CREATE_USER_REQUEST',
  CREATE_USER_SUCCESS: '@users/CREATE_USER_SUCCESS',

  DELETE_USER_REQUEST: '@users/DELETE_USER_REQUEST',
  DELETE_USER_SUCCESS: '@users/DELETE_USER_SUCCESS',

  UPDATE_USER_REQUEST: '@users/UPDATE_USER_REQUEST',
  UPDATE_USER_SUCCESS: '@users/UPDATE_USER_SUCCESS',
};

export default Types;
